// flow-typed signature: 0863006fe312a76ced38d5edf380d69d
// flow-typed version: <<STUB>>/react-axios_v^1.0.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-axios'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-axios" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "react-axios/es/components/AxiosProvider" {
  declare module.exports: any;
}

declare module "react-axios/es/components/Request" {
  declare module.exports: any;
}

declare module "react-axios/es/components/RequestWrapper" {
  declare module.exports: any;
}

declare module "react-axios/es/index" {
  declare module.exports: any;
}

declare module "react-axios/es/utils/index" {
  declare module.exports: any;
}

declare module "react-axios/lib/components/AxiosProvider" {
  declare module.exports: any;
}

declare module "react-axios/lib/components/Request" {
  declare module.exports: any;
}

declare module "react-axios/lib/components/RequestWrapper" {
  declare module.exports: any;
}

declare module "react-axios/lib/index" {
  declare module.exports: any;
}

declare module "react-axios/lib/utils/index" {
  declare module.exports: any;
}

declare module "react-axios/umd/ReactAxios" {
  declare module.exports: any;
}

declare module "react-axios/umd/ReactAxios.min" {
  declare module.exports: any;
}

// Filename aliases
declare module "react-axios/es/components/AxiosProvider.js" {
  declare module.exports: $Exports<"react-axios/es/components/AxiosProvider">;
}
declare module "react-axios/es/components/Request.js" {
  declare module.exports: $Exports<"react-axios/es/components/Request">;
}
declare module "react-axios/es/components/RequestWrapper.js" {
  declare module.exports: $Exports<"react-axios/es/components/RequestWrapper">;
}
declare module "react-axios/es/index.js" {
  declare module.exports: $Exports<"react-axios/es/index">;
}
declare module "react-axios/es/utils/index.js" {
  declare module.exports: $Exports<"react-axios/es/utils/index">;
}
declare module "react-axios/lib/components/AxiosProvider.js" {
  declare module.exports: $Exports<"react-axios/lib/components/AxiosProvider">;
}
declare module "react-axios/lib/components/Request.js" {
  declare module.exports: $Exports<"react-axios/lib/components/Request">;
}
declare module "react-axios/lib/components/RequestWrapper.js" {
  declare module.exports: $Exports<"react-axios/lib/components/RequestWrapper">;
}
declare module "react-axios/lib/index.js" {
  declare module.exports: $Exports<"react-axios/lib/index">;
}
declare module "react-axios/lib/utils/index.js" {
  declare module.exports: $Exports<"react-axios/lib/utils/index">;
}
declare module "react-axios/umd/ReactAxios.js" {
  declare module.exports: $Exports<"react-axios/umd/ReactAxios">;
}
declare module "react-axios/umd/ReactAxios.min.js" {
  declare module.exports: $Exports<"react-axios/umd/ReactAxios.min">;
}
